association:
  center_dist_px: 150
  head_crop_ratio_top: 0.4
  iou_person_bike: 0.1
detector:
  agnostic_nms: false
  conf: 0.25
  iou: 0.5
  max_det: 300
plate:
  min_crop_h: 12
  min_crop_w: 40
  ocr: easyocr
rules:
  temporal_window_s: 0.5
  triple_riding_min_persons: 3
  vote_window: 5
tracker:
  frame_rate: 30.0
  match_thresh: 0.8
  track_buffer: 30
  track_thresh: 0.5
  type: bytetrack
